### ISSUE TITLE
pg-promise misuse

### ISSUE THREAD

**Issue by vitaly-t** [fibo/read-file-utf8#2]
What you are showing in your examples, pg-promise has a far better support of:
- [Query Files in documentation](https://github.com/vitaly-t/pg-promise#query-files)
- [QueryFile API](http://vitaly-t.github.io/pg-promise/QueryFile.html)
- [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) - shows how to properly organize SQL.

I'm guessing that somehow you have missed all that :)

**Comment by fibo** [comment]
should be fixed now, thank you for reporting it

**Comment by vitaly-t** [comment]
Ok, but I still wonder, why use this with pg-promise which has a better support for SQL files?

Type [QueryFile](http://vitaly-t.github.io/pg-promise/QueryFile.html) can parse and minify SQL, it can watch for changes in debug mode and automatically re-load SQL, it can be used directly with query methods, etc...

B.T.W. pg-promise makes use of [pg-minify](https://github.com/vitaly-t/pg-minify), to parse and minify the SQL (remove comments and shrink to a single line).

**Comment by fibo** [comment]
Is just an example, in fact I changed the section title from **Use case** to **Example** with a link to pg-promise file api.

**Comment by fibo** [comment]
I removed pg-promise example, sorry for the misuse.

**Comment by vitaly-t** [comment]
I didn't really mind. But I couldn't understand why in the context of pg-promise you wrote this in the first place.

If you compare to what type `QueryFile` can do:
- It can do basic SQL parsing for errors after loading it up;
- It can minify the SQL (remove all the comments - both single-line and multi-line ones), and turn it into a single SQL line
- It can compress the SQL (remove all unneeded spaces)
- In debug mode it can detect any changes in the external SQL and automatically reload it whenever the next query is called. This dramatically reduces the development time, as one can see changes in the app without restarting it.
- It has automatic type support, which means one can pass variable of type `QueryFile` directly into any query method.
- It can apply static formatting to the loaded SQL, to allow two-stage formatting (very useful).
- It allows late error reporting, integrating into the common promise stream, making it so much easier to handle.

My understanding, your library can do none of that, hence was my question why.

You can use type `QueryFile` from pg-promise independently of the rest:

``` js
var QueryFile = require('pg-promise').QueryFile;
```

**Comment by fibo** [comment]
I will check it out, thanks for the detailed feature list.
I am not attracted by minification or compress feature. Usually I write a query in psql, and version it after it s working. I use it later with some library like pg-promise that I found really useful and mature lib, ubt, I prefer to keep SQL in its original environment, that is int this case, the great psql session cli.

**Comment by fibo** [comment]
Eheh, also a curiosity. I immagine you have some bot that finds for you where the string pg-promise is, otherwise I do not understand how you found it in my tiny package :)

**Comment by vitaly-t** [comment]
> I am not attracted by minification or compress feature. Usually I write a query in psql, and version it after it s working.

Within pg-promise all that is done by [pg-minify](https://github.com/vitaly-t/pg-minify), in case you change your mind. People like writing large SQL, with lots of comments in them. There is no reason executing it all on every query, only uses extra resources. Plus it fixes multi-line text, which can be very useful. Compressed SQL is always better ;)

> I immagine you have some bot that finds for you where the string pg-promise is, otherwise I do not understand how you found it in my tiny package :)

Not really. GitHub search engine can show you all the recent references to your library. I just see the list whenever someone checks in the code that uses pg-promise ;)
